// Code generated by MockGen. DO NOT EDIT.
// Source: google_cloud_storage_client.go

// Package google_cloud_storage is a generated GoMock package.
package google_cloud_storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SignedUrl mocks base method.
func (m *MockRepository) SignedUrl(ctx context.Context, filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignedUrl", ctx, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignedUrl indicates an expected call of SignedUrl.
func (mr *MockRepositoryMockRecorder) SignedUrl(ctx, filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignedUrl", reflect.TypeOf((*MockRepository)(nil).SignedUrl), ctx, filePath)
}
