// Code generated by MockGen. DO NOT EDIT.
// Source: ./file_upload.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileUploadRepository is a mock of FileUploadRepository interface.
type MockFileUploadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileUploadRepositoryMockRecorder
}

// MockFileUploadRepositoryMockRecorder is the mock recorder for MockFileUploadRepository.
type MockFileUploadRepositoryMockRecorder struct {
	mock *MockFileUploadRepository
}

// NewMockFileUploadRepository creates a new mock instance.
func NewMockFileUploadRepository(ctrl *gomock.Controller) *MockFileUploadRepository {
	mock := &MockFileUploadRepository{ctrl: ctrl}
	mock.recorder = &MockFileUploadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUploadRepository) EXPECT() *MockFileUploadRepositoryMockRecorder {
	return m.recorder
}

// GetSignedURL mocks base method.
func (m *MockFileUploadRepository) GetSignedURL(ctx context.Context, req *GetSignedURLRequest) (*GetSignedURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignedURL", ctx, req)
	ret0, _ := ret[0].(*GetSignedURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignedURL indicates an expected call of GetSignedURL.
func (mr *MockFileUploadRepositoryMockRecorder) GetSignedURL(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignedURL", reflect.TypeOf((*MockFileUploadRepository)(nil).GetSignedURL), ctx, req)
}

// UploadFile mocks base method.
func (m *MockFileUploadRepository) UploadFile(ctx context.Context, req *UploadFileRequest) (*UploadFileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, req)
	ret0, _ := ret[0].(*UploadFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileUploadRepositoryMockRecorder) UploadFile(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileUploadRepository)(nil).UploadFile), ctx, req)
}
